Hyper Parameter Ridge Regression_Params:
  alpha: 1
  copy_X: true
  fit_intercept: true
  max_iter:
  positive: false
  random_state:
  solver: lsqr
  tol: 1e-06
Hyper Parameter Support Vector Regression_Params:
  C: 0.6
  cache_size: 200
  coef0: 0.0
  degree: 3
  epsilon: 0.01
  gamma: scale
  kernel: rbf
  max_iter: -1
  shrinking: true
  tol: 0.001
  verbose: false
Hyper Parameter Randomn Forrest Regression_Params:
  bootstrap: true
  ccp_alpha: 0.0
  criterion: squared_error
  max_depth:
  max_features: log2
  max_leaf_nodes:
  max_samples:
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  monotonic_cst:
  n_estimators: 256
  n_jobs:
  oob_score: false
  random_state:
  verbose: 0
  warm_start: false
Hyper Parameter Gradient Boost Regression_Params:
  alpha: 0.9
  ccp_alpha: 0.0
  criterion: friedman_mse
  init:
  learning_rate: 0.05
  loss: squared_error
  max_depth: 3
  max_features:
  max_leaf_nodes:
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  n_estimators: 256
  n_iter_no_change:
  random_state:
  subsample: 0.8
  tol: 0.0001
  validation_fraction: 0.1
  verbose: 0
  warm_start: false
Hyper Parameter XGBoost Regression_Params:
  objective: reg:squarederror
  base_score:
  booster:
  callbacks:
  colsample_bylevel:
  colsample_bynode:
  colsample_bytree:
  device:
  early_stopping_rounds:
  enable_categorical: false
  eval_metric:
  feature_types:
  feature_weights:
  gamma:
  grow_policy:
  importance_type:
  interaction_constraints:
  learning_rate: 0.1
  max_bin:
  max_cat_threshold:
  max_cat_to_onehot:
  max_delta_step:
  max_depth:
  max_leaves:
  min_child_weight:
  missing: .nan
  monotone_constraints:
  multi_strategy:
  n_estimators: 128
  n_jobs:
  num_parallel_tree:
  random_state:
  reg_alpha:
  reg_lambda:
  sampling_method:
  scale_pos_weight:
  subsample:
  tree_method:
  validate_parameters:
  verbosity:
